# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.0.x version
  - 7.0

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - composer install

script:
  - ./vendor/bin/atoum -c .atoum.php -d test/unit/src -utr
  - chmod +x test/run/installer
  - cd $TRAVIS_BUILD_DIR/test/run && ./installer

after_script:
 ## Scrutinizer
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover clover.xml